### This is the uv init sentinel. Any content above this line should be removed during the generation
### process.
###
### `uv init` will add content to __init__.py upon its initial generation, but we don't want the
### content to be a part of the final output. So, during the generation process, search for this
### comment and remove it and everything that comes before it. We search for a sentinel rather than
### specific content because the content generated by `uv init` may change over time, but this
### sentinel will remain the same.
# noqa: D104

from importlib.metadata import version


__version__ = version("{{ python_package_name }}")
